network: malunet
model_config:
  num_classes: 1
  input_channels: 3
  c_list: [ 8, 16, 24, 32, 48, 64 ]
  split_att: fc
  bridge: true
test_weights: ''

datasets: isic16
dataset_path: ./data/isic2016/
gt_format: '{}_Segmentation.png'

criterion: BceDiceLoss
num_classes: 1
input_size_h: 256
input_size_w: 256
input_channels: 3
distributed: false
local_rank: -1
num_workers: 0
seed: 42
world_size: null
rank: null
amp: false
batch_size: 8
epochs: 300
work_dir: results/malunet/isic18/
print_interval: 20
val_interval: 30
save_interval: 100
threshold: 0.5
opt: AdamW
lr: 0.001
betas: [ 0.9, 0.999 ]
eps: 0.00000001
weight_decay: 0.01
amsgrad: false
sch: CosineAnnealingLR
T_max: 50
# 1e-05
eta_min: 0.00001
last_epoch: -1
